//
/*:
 * @plugindesc 语言文本.
 * @author 杨志（yang1zhi）落泪
 * @help  yangzhi40#hotmail.com
 * 语言插件的文字板块
 *  中文
 * 版本：1.0
 * yangzhi40@hotmail.com
 */

YUYAN_QIEHUAN[2] = {
    ZHONGYAO: {
        //哪国文字
        guojia: "English",
        //语言
        language: "language",
    },

    YOUXI_WENBEN: {},
    SHUJUKU_YONGYU: {
        actor_name: {
            1: "Mydei",
            2: "Phainon",
            3: "Khaslana",
            4: "Mifamem",
        },
        actor_nickname: {},
        actor_profile: {},
        classs_name: {},
        skill_name: {
            1: "攻击",
            2: "防御",
            3: "连续攻击",
            4: "两次攻击",
            5: "三次攻击",
            6: "逃跑",
            7: "观望",
            8: "治愈",
            9: "火焰",
            10: "闪电",
        },
        skill_description: {},
        skill_message1: {
            1: "的攻击！",
            2: "正在保护自己。",
            3: "的攻击！",
            4: "的攻击！",
            5: "的攻击！",
            6: "逃跑了。",
            7: "正在观望。",
            8: "吟唱了%1！",
            9: "吟唱了%1！",
            10: "吟唱了%1！",
        },
        skill_message2: {},
        item_name: {
            1: "The Blank Oracle Card",
            2: "Drift Bottle",
            3: "Letters in the Drift Bottle",
            4: "死亡火种",
            5: "天空火种",
            6: "浪漫火种",
            7: "门径火种",
            8: "理性火种",
            9: "诡计火种",
            10: "图书馆钥匙",
            11: "碎瓷片",
            12: "悬锋字典",
            13: "2 letters from Mifamem",
            14: "纷争火种",
            15: "负世火种",
            16: "那刻夏要的东西",
            17: "Old ham",
            18: "Vege",
        },
        item_description: {
            17: "白厄送给小妖精的腌肉，看起来还没坏。",
            18: "生菜、南瓜、玉米、土豆、番茄、洋葱、\n绿球菜、荚荚豆、蜜果干",
        },
        weapon_name: {
            1: "剑",
            2: "斧",
            3: "杖",
            4: "弓",
        },
        weapon_description: {},
        armors_name: {
            1: "盾牌",
            2: "帽子",
            3: "衣服",
            4: "戒指",
        },
        armors_description: {},
        enemie_name: {
            1: "蝙蝠",
            2: "史莱姆",
            3: "兽人",
            4: "牛头怪",
        },
        troop_name: {
            1: "蝙蝠*2",
            2: "史莱姆*2",
            3: "兽人",
            4: "牛头怪",
        },
        state_name: {
            1: "无法战斗",
            2: "防御",
            3: "不死之身",
            4: "中毒",
            5: "黑暗",
            6: "沉默",
            7: "愤怒",
            8: "混乱",
            9: "魅惑",
            10: "睡眠",
        },
        state_message1: {
            1: "倒下了！",
            4: "中毒了！",
            5: "陷入了黑暗！",
            6: "沉默了！",
            7: "被激怒了！",
            8: "陷入了混乱！",
            9: "被魅惑了！",
            10: "睡着了！",
        },
        state_message2: {
            1: "被打败了！",
            4: "中毒了！",
            5: "陷入了黑暗！",
            6: "沉默了！",
            7: "被激怒了！",
            8: "陷入了混乱！",
            9: "被魅惑了！",
            10: "睡着了！",
        },
        state_message3: {
            10: "正在沉睡中。",
        },
        state_message4: {
            1: "复活了！",
            4: "中的毒消失了！",
            5: "的黑暗消失了！",
            6: "的沉默解除了！",
            7: "恢复了理智！",
            8: "恢复了理智！",
            9: "恢复了理智！",
            10: "醒来了！",
        },
        animation_name: {
            1: "打击/物理",
            2: "打击/特效",
            3: "打击/炎",
            4: "打击/冰",
            5: "打击/雷",
            6: "斩击/物理",
            7: "斩击/特效",
            8: "斩击/炎",
            9: "斩击/冰",
            10: "斩击/雷",
            11: "突刺/物理",
            12: "突刺/特效",
            13: "突刺/火",
            14: "突刺/冰",
            15: "突刺/雷",
            16: "爪/物理",
            17: "爪/特效",
            18: "爪/火",
            19: "爪/冰",
            20: "爪/雷",
            21: "打击/必杀技 1",
            22: "打击/必杀技 2",
            23: "斩击/必杀技 1",
            24: "斩击/必杀技 2",
            25: "斩击/必杀技 3",
            26: "突刺/必杀技 1",
            27: "突刺/必杀技 2",
            28: "爪/必杀技",
            29: "箭/必杀技",
            30: "通用/必杀技 1",
            31: "通用/必杀技 2",
            32: "吐息",
            33: "花粉",
            34: "超音波",
            35: "雾",
            36: "歌",
            37: "咆哮",
            38: "扫堂腿",
            39: "冲撞",
            40: "闪光",
            41: "恢复/单体 1",
            42: "恢复/单体 2",
            43: "恢复/全体 1",
            44: "恢复/全体 2",
            45: "治疗/单体 1",
            46: "治疗/单体 2",
            47: "治疗/全体 1",
            48: "治疗/全体 2",
            49: "复活 1",
            50: "复活 2",
            51: "强化 1",
            52: "强化 2",
            53: "强化 3",
            54: "弱化 1",
            55: "弱化 2",
            56: "弱化 3",
            57: "束缚",
            58: "吸收",
            59: "毒",
            60: "黑暗",
            61: "沉默",
            62: "睡眠",
            63: "混乱",
            64: "麻痹",
            65: "即死",
            66: "炎/单体 1",
            67: "炎/单体 2",
            68: "炎/全体 1",
            69: "炎/全体 2",
            70: "炎/全体 3",
            71: "冰/单体 1",
            72: "冰/单体 2",
            73: "冰/单体 3",
            74: "冰/全体 2",
            75: "冰/全体 3",
            76: "雷/单体 1",
            77: "雷/单体 2",
            78: "雷/全体 1",
            79: "雷/全体 2",
            80: "雷/全体 3",
            81: "水/单体 1",
            82: "水/单体 2",
            83: "水/全体 1",
            84: "水/全体 2",
            85: "水/全体 3",
            86: "土/单体 1",
            87: "土/单体 2",
            88: "土/全体 1",
            89: "土/全体 2",
            90: "土/全体 3",
            91: "风/单体 1",
            92: "风/单体 2",
            93: "风/全体 1",
            94: "风/全体 2",
            95: "风/全体 3",
            96: "光/单体 1",
            97: "光/单体 2",
            98: "光/全体 1",
            99: "光/全体 2",
            100: "光/全体 3",
            101: "暗/单体 1",
            102: "暗/单体 2",
            103: "暗/全体 1",
            104: "暗/全体 2",
            105: "暗/全体 3",
            106: "无属性/单体 1",
            107: "无属性/单体 2",
            108: "无属性/全体 1",
            109: "无属性/全体 2",
            110: "无属性/全体 3",
            111: "铳击/单发",
            112: "铳击/连发",
            113: "铳击/全体",
            114: "铳击/必杀技",
            115: "激光/单发",
            116: "激光/全体",
            117: "光柱 1",
            118: "光柱 2",
            119: "光弹",
            120: "射线",
        },
        Tileset_name: {
            1: "世界",
            2: "世界透明",
            3: "ox关门",
            4: "ox开门",
            5: "ox透明",
        },
        CommonEvent_name: {
            1: "Oracle Card",
            2: "Letters in the Drift Bottle",
            3: "2 Letters from Mifamem",
        },
        CommonEvent_TXT: {
            1: {
                6: "The oracle card directs you to the Lost Maze",
                9: "??:",
                10: "Mew!? Who's out there!",
                12: "A little fairy? Go check it out.",
                21: "The oracle card directs you to the Lost Maze",
                31: "The oracle card directs you to the Grove of Epiphany",
                43: "The oracle card directs you to the Castrum Kremnos Library",
                55: "The oracle card directs you to the Castrum Kremnos Library",
                67: "The oracle card directs you to the Dawn Cloud Crag",
                79: "The oracle card directs you to the top of Dawn Cloud Crag to examine the Dawn Machine",
                88: "A blank oracle card",
                89: "When investigating important items, it guides the way",
                90: "When you have no direction, try looking around for interactable objects",
            },
        },
        CommonEvent_TXT_Choices: {
            2: {
                18: ["收起", "翻页", ],
                27: ["收起", "翻页", ],
                62: ["收起", "翻页", ],
                71: ["收起", "翻页", ],
                80: ["收起", "翻页", ],
            },
            3: {
                18: ["下一页", "收起", ],
                24: ["下一页", "收起", "上一页", ],
                30: ["上一页", "收起", ],
            },
        },
        System_gameTitle: "敌厄游戏流程测试",
        System_currencyUnit: "G",
        System_elements: ["", "物理", "炎", "冰", "雷", "水", "土", "风", "光", "暗", ],
        System_skillTypes: ["", "魔法", "必杀技", ],
        System_weaponTypes: ["", "匕首", "剑", "流星锤", "斧", "鞭", "杖", "弓箭", "弩", "枪", "爪", "手套", "矛", ],
        System_armorTypes: ["", "一般护甲", "魔法护甲", "轻型护甲", "重型护甲", "小型盾牌", "大型盾牌", ],
        System_equipTypes: ["", "武器", "盾牌", "头部", "身体", "装饰品", ],
        System_basic: ["等级", "Lv", "HP", "HP", "MP", "MP", "TP", "TP", "经验值", "EXP", ],
        System_params: ["最大 HP", "最大 MP", "攻击力", "防御力", "魔法攻击", "魔法防御", "敏捷", "幸运", "命中率", "回避率", ],
        System_commands: ["战斗", "逃跑", "攻击", "防御", "Item", "技能", "装备", "状态", "整队", "Save", "Quit", "Setting", "武器", "护甲", "重要物品", "装备", "最强装备", "清空", "Start Game", "Load Game", "null", "Return Homepage", "Cancel", "null", "购买", "出售", ],
        System_messages: {
            actionFailure: "对%1没有效果！",
            actorDamage: "%1受到了 %2 点伤害！",
            actorDrain: "%1被吸收了 %3 点 %2！",
            actorGain: "%1的 %2 增加了 %3 点！",
            actorLoss: "%1的 %2 减少了 %3 点！",
            actorNoDamage: "%1没有受到伤害！",
            actorNoHit: "Miss！ %1没有受到伤害！",
            actorRecovery: "%1恢复了 %3 点 %2！",
            alwaysDash: "始终跑步",
            bgmVolume: "BGM 音量",
            bgsVolume: "BGS 音量",
            buffAdd: "%1的%2上升了！",
            buffRemove: "%1的%2恢复正常了！",
            commandRemember: "记住指令",
            counterAttack: "%1的反击！",
            criticalToActor: "痛恨一击！",
            criticalToEnemy: "会心一击！",
            debuffAdd: "%1的%2下降了！",
            defeat: "%1被击败了。",
            emerge: "%1出现了！",
            enemyDamage: "%1受到了 %2 点伤害！",
            enemyDrain: "%1被吸收了 %3 点 %2！",
            enemyGain: "%1的 %2 增加了 %3 点！",
            enemyLoss: "%1的 %2 减少了 %3 点！",
            enemyNoDamage: "没有对%1造成伤害！",
            enemyNoHit: "Miss！没有对%1造成伤害！",
            enemyRecovery: "%1恢复了 %3 点 %2！",
            escapeFailure: "但是没有逃跑成功！",
            escapeStart: "%1开始逃跑了！",
            evasion: "%1躲开了攻击！",
            expNext: "距离下一%1",
            expTotal: "现在的%1",
            file: "文件",
            levelUp: "%1升到了 %2 %3！",
            loadMessage: "读取哪个文件？",
            magicEvasion: "%1抵消了魔法！",
            magicReflection: "%1反射了魔法！",
            meVolume: "ME 音量",
            obtainExp: "获得了 %1 点%2！",
            obtainGold: "获得了 %1\G！",
            obtainItem: "获得了%1！",
            obtainSkill: "学会了%1！",
            partyName: "%1的队伍",
            possession: "持有数",
            preemptive: "%1先发制人！",
            saveMessage: "保存到哪个文件？",
            seVolume: "SE 音量",
            substitute: "%1保护了%2！",
            surprise: "%1被偷袭了！",
            useItem: "%1使用了%2！",
            victory: "%1胜利了！",
        },
        System_map: {},
        Event_txt: {
            1: {
                32: {
                    0: {
                        1: "迷宫测试",
                        2: "钻石是出口，但只有按照特定方式才能正确激活出口。",
                        8: "粉色、黄色、绿色、蓝色、紫色、白色、钻石",
                    },
                    1: {
                        1: "迷宫测试",
                        2: "钻石是出口，但只有按照特定方式才能正确激活出口。",
                        8: "粉色、黄色、绿色、蓝色、紫色、白色、钻石",
                    },
                },
            },
            2: {
                1: {
                    0: {
                        1: "通关！",
                        2: "特别鸣谢帮我测试的：启悦",
                    },
                },
            },
            3: {
                1: {
                    0: {
                        3: "There's a letter inside.",
                        6: "The Oracle Card sence something, have a check",
                        7: "【Item】→【Oracal Card】→【Confirm】→【Confirm】",
                    },
                },
                2: {
                    0: {
                        7: "试试用神谕牌",
                        11: "看起来完全没有入口，但我的嗅觉不可能",
                        12: "出错。是用什么办法藏起来了？",
                    },
                },
                3: {
                    0: {
                        5: "<wrap>It's Aedes Elysiae after the disaster...",
                        12: "<wrap>Just as expected.",
                        20: "<wrap>Mew... Intense memories of destruction are flooding into me, this space... is weeping to me!",
                        22: "<wrap>Are you okay? If you can't handle it, go out first.",
                        24: "<wrap>Do you sense anything?",
                        26: "<wrap>The smell of rust, the smell of burning...",
                        32: "<wrap>There's vegetation not completely destroyed to the west, and a slightly damp smell over there. I guess there's an underground cavity.",
                        34: "<wrap>Phainon said you're a beast, and he wasn't wrong... Then please take this!",
                        40: "<wrap>Isn't this the divination cards you always carry?",
                        42: "<wrap>(Flips it over) The card face is blank?",
                        44: "<wrap>That's right, this is a blank oracle card. When you find clues, the blank space on the card will show you the path.",
                        46: "<wrap>Then I'll head out first.",
                        48: "<wrap>See you.",
                        59: "<wrap>A Realm Anchor here?",
                        62: "<wrap>\\c[4]Realm Anchor\\c[0] is a save point! Remember to save!<br><br>\\c[2]To load a save, return to the title screen.",
                    },
                },
                4: {
                    1: {
                        9: "<wrap>You're back? Hey, why the long face?",
                        11: "<wrap>I lost another bet to the fairies...",
                        13: "<wrap>Did you lose the wooden sword your dad made for you again?",
                        15: "<wrap>Mm...",
                        17: "<wrap>Oh dear, while most of the fairies' bets are harmless, why can't you just say no to them?",
                        19: "<wrap>After they heard I'm going to Castrum Kremnos to learn swordsmanship, they didn't want me to leave. Mifamem kept clinging to me. And now I have to remember all the gifts they wished for from me!",
                        21: "<wrap>They also hope that after I leave Ailimixie, I'll learn a few local specialty dishes from other places and come back to cook for them.",
                        23: "<wrap>Seriously, it's not like I'm going to Le Cordon Bleu—unless the motto of the Castrum Kremnos soldiers is \"A warrior who can't cook isn't a good general\"!",
                        25: "<wrap>Hehehe! Amphoreus is so vast—maybe you'll actually find a Castrum Kremnos leader who excels both on the battlefield and in the kitchen!",
                        27: "<wrap>Ah! Great Kephale and Oronyx! Please grant me such a person from Castrum Kremnos! For the sake of the little fairies' wishes!",
                        29: "<wrap>As for the little fairies' wishes... I think",
                        31: "<wrap>As long as you don't forget the little fairies and remember to bring new friends back to visit them, that itself is the best gift for them!",
                        38: "<wrap>Do you still... remember now... Khaslana...",
                        40: "…………",
                        46: "<wrap>\"A warrior who can't cook isn't a good general\"... Hmph.",
                    },
                },
                6: {
                    1: {
                        9: "<wrap>Why did it have to turn out this way...!!",
                        11: "<wrap>I should never have planned to go to Castrum Kremnos to learn swordsmanship—then I wouldn't have missed the chance to stop the black tide in the first place because I was packing my bags!!",
                        17: "<wrap>...That logic doesn't hold up.",
                        23: "...",
                    },
                },
                7: {
                    1: {
                        9: "<wrap>How could I possibly forget the little fairies just because I grow up? Cyrene must be teasing me.",
                        11: "<wrap>Livia didn't follow me, did she? Good, good... If she found out, she'd definitely pester me and try to sneak a peek at what I've written. No way, no way.",
                        13: "<wrap>(Sets down the bottle) Drift away! Don't ever come back...",
                        15: "<wrap>If you absolutely must come back, please return secretly in the far, far future!",
                        21: "<wrap>...Can't find...",
                        29: "<wrap>So that's the story behind the letter in a bottle I just picked up.",
                        33: "<wrap>What are you looking for?",
                        38: "<wrap>A drift bottle?",
                    },
                },
            },
            4: {
                24: {
                    0: {
                        2: "<wrap>It seems... I'm back where I started... I remember Phainon's letter had instructions on how to navigate this maze.",
                    },
                },
                37: {
                    0: {
                        4: "<wrap>(It's so dark, I can't see anything... Wait, something is rubbing against me!)",
                        19: "<wrap>Who goes there!?",
                        21: "<wrap>(Fumbling in my pocket) My oracle card!?",
                        23: "<wrap>You can't escape!",
                        25: "\\c[2]The giant diamond is a placeholder for the entrance\\c[0]",
                        26: "The final version will change the entrance to a tree hollow with flowers of corresponding colors",
                    },
                },
            },
            5: {
                1: {
                    0: {
                        7: "<wrap>What!? You actually made it out, mew!!",
                        9: "<wrap>Stop running!",
                    },
                    2: {
                        3: "<wrap>No prey can escape a Kremnoan's spear, unless you kill me.",
                        5: "<wrap>Help! Somebody help me, mew!! I didn't mean it, mew, it, it was the village chief who told me to do it!",
                        7: "<wrap>Where's the oracle card?",
                        9: "<wrap>At the village chief's place!",
                        14: "<wrap>Then you're coming with me to find your village chief. (Drags away)",
                        17: "<wrap>Waaah, Kremnoans are so scary, mew...",
                    },
                },
                3: {
                    0: {
                        1: "<wrap>(Takes out the oracle card)",
                        4: "<wrap>Leave here and then find the way to the Grove?",
                        7: "<wrap>Mew!",
                        13: "<wrap>The spatial laws in this Memory Domain are different from reality, so the oracle card has opened a portal for you.",
                        15: "<wrap>Oh?",
                        17: "<wrap>Just touch it directly!",
                    },
                },
                5: {
                    0: {
                        2: "<wrap>Chief!",
                        6: "<wrap>Oh my, Mifamem, you've brought him here.",
                        8: "<wrap>Is the etiquette of you fairies towards a friend's friend to lure them into a maze and trap them?",
                        10: "<wrap>Too bad, your tricks might work on a young Phainon who hasn't grown up, but trying them on me is outdated.",
                        12: "<wrap>Well, it's been a long time since we've had a guest in the Membrance Maze... now that a stranger has appeared, it's normal for the children to be wary.",
                        14: "<wrap>Chief, he has another letter on him, it must be from Phainon! He stole it!",
                        16: "?",
                        18: "<wrap>We've got him surrounded now, quick, use the Mem-fist on him!",
                        20: "<wrap>Go ahead and try. (Holding back laughter)",
                        22: "<wrap>(Hesitant) But Mifamem, I think our little fists would just be tickling him...",
                        24: "<wrap>Hey——everyone, calm down first.",
                        27: "<wrap>Kremnoan warrior, this is your oracle card.",
                        29: "<wrap>(Examines the card) (No reaction from the card)",
                        31: "<wrap>Mifamem, you can't say things like that just now. Aren't you falsely accusing our guest?",
                        33: "<wrap>If you wanted to see the letter, why didn't you just ask me?",
                        37: "<wrap>Mydei shows the letter from the bottle to the little fairies.",
                        40: "<wrap>It... it was just a letter from a long time ago... sob...",
                        42: "<wrap>Snowy really has forgotten us...",
                        44: "<wrap>Nonsense! Snowy must be busy!",
                        46: "<wrap>But, Snowy forgetting us might actually be the better outcome. If he hadn't forgotten, but couldn't come, wouldn't that mean...",
                        48: "<wrap>I don't want to imagine the worst... but...",
                        50: "<wrap>Snowy can't be dead! He's Aedes Elysiae's strongest warrior!",
                        52: "<wrap>Maybe Phainon lost his innocent heart, so he can't enter the Membrance Maze anymore.",
                        54: "<wrap>This Kremnoan can enter, so Snowy definitely could too.",
                        56: "<wrap>What are you implying.",
                        58: "<wrap>Oh! Hey, Kremnoan, don't you claim to be Phainon's friend? You must know what's going on with Snowy!",
                        60: "<wrap>Is Snowy still alive?",
                        62: "...",
                        64: "<wrap>(Reminiscing)<br>Phainon is trapped by Lygus. I don't know where he is, but he must still be holding on. He's still waiting for us.",
                        66: "<wrap>(Frowns) He...",
                        68: "<wrap>Why are you hesitating!? Is Snowy really dead?",
                        70: "<wrap>No, he's just, he's just very busy.",
                        72: "<wrap>You hesitated, you're lying to us.",
                        74: "<wrap>Ahem, I'm not lying. Phainon really isn't dead.",
                        76: "<wrap>(Seeing the tears welling up in Mifamem's eyes, seeing the expectant yet fearful looks of the little fairies—this bunch of little creatures truly cares about that HKS.)",
                        78: "<wrap>(Sighs)... Didn't you want Phainon to learn some Kremnoan specialty dishes from Castrum Kremnos and come back to cook them for you? He couldn't make it, so he sent me instead.",
                        80: "<wrap>Really?",
                        82: "<wrap>Let me properly introduce myself then.",
                        84: "<wrap>I am a comrade-in-arms of Phainon the Deliverer, King of Castrum Kremnos, and Demigod of Strife, Mydeimos. You can call me Mydei.",
                        86: "<wrap>(Stunned)",
                        88: "<wrap>(Stunned) Deliverer, Phainon?",
                        90: "<wrap>(Stunned) Demigod of Strife?",
                        92: "<wrap>(Stunned) Kremnoan King? Cooking for us?",
                        94: "<wrap>Just think of me as Phainon's friend.",
                        96: "<wrap>So, do you have any ingredients? Where should I set up the pot later?",
                        98: "<wrap>(Stunned)",
                        113: "<wrap>Ah! Mifamem, quick, take His Majesty Mydeimos to our granary.",
                        116: "<wrap>Other fairies, come with me to the banquet platform to set up the pots.",
                        118: "<wrap>You don't need to set up pots. I'll do it myself.",
                        120: "<wrap>This way!",
                    },
                },
                6: {
                    2: {
                        2: "<wrap>(Whispering) Cyrene, Cyrene",
                        5: "<wrap>Mew!",
                        11: "<wrap>Oh, you entered the Membrance Maze?",
                        13: "<wrap>I want to cook for the little fairies, but there's no meat. Can you help?",
                        15: "<wrap>Cooking...? I see.",
                        17: "<wrap>If you need meat, I remember Phainon did send some cured meat to the little fairies. But they don't know how to cook it, and they don't like eating it dry, so it's been sitting at the bottom of the storage. They probably forgot about it over time.",
                        19: "<wrap>Follow me.",
                    },
                },
                7: {
                    1: {
                        2: "<wrap>These are the crops we harvested before, mew.",
                        4: "<wrap>Why isn't there any meat? It's all just grass!",
                        6: "<wrap>Mew!? Is that not okay? Hmm, you didn't bring any meat?",
                        8: "<wrap>...Wait for me here.",
                        12: "<wrap>(Go somewhere farther to call for Cyrene)",
                    },
                    2: {
                        3: "<wrap>Got the meat? (Sniff sniff)",
                        5: "<wrap>Yeah. I'll make a few small portions to try first.",
                        12: "<wrap>Meat?",
                        14: "<wrap>Not yet.",
                    },
                },
                12: {
                    0: {
                        3: "<wrap>Here?",
                        5: "<wrap>Yes!",
                    },
                    1: {
                        6: "<wrap>Wow, it's so dusty.",
                    },
                },
                14: {
                    0: {
                        2: "<wrap>Found it!",
                        5: "<wrap>...In such a humid environment? How many years old is this cured meat?",
                        7: "<wrap>Actually, it won't spoil. Although the maze is generally humid, the tree hollow is very dry. But to be safe, you can check it. I'm sure this won't stump our Kremnoan chef!",
                        9: "<wrap>(Sighs)",
                        18: "<wrap>Miss Cyrene, aren't you coming with me?",
                        20: "<wrap>I won't go. Here, I can only appear in this form.",
                        22: "<wrap>The fairies all know that whenever a major disaster happens in the outside world, one more fairy appears in the maze. If everyone saw a Cyrene like this, they probably wouldn't be in the mood to eat your cooking.",
                        24: "<wrap>...I see.",
                        26: "<wrap>See you later, mew! Call me if you need anything!",
                        30: "<wrap>(Go find Mifamem)",
                    },
                },
                15: {
                    1: {
                        1: "<wrap>Mydei quickly set up a stove in the cooking area.<br>Kremnoan infrastructure amazed the fairies.<br>After some fiddling, he brought out a few small dishes, and the fairies couldn't wait to swarm them.",
                        3: "<wrap>After a little commotion, the fairies cleared the few samples and began licking their paws, still wanting more.",
                        7: "<wrap>Didn't get enough, mew...",
                        9: "<wrap>Which one do you like? I'll make more.",
                        11: "<wrap>Wait, Mydei, can you teach me?",
                        13: "<wrap>Huh?",
                        15: "<wrap>(This guy is like Phainon)",
                        17: "<wrap>What dish do you want to learn?",
                        19: "<wrap>All of them!",
                        22: "<wrap>Come.",
                    },
                },
                18: {
                    1: {
                        5: "<wrap>Thank you so much, Your Majesty Mydeimos. The children haven't heard news of Phainon and Cyrene for a long time, and this is the first time they've eaten such delicious Kremnoan cuisine.",
                        14: "<wrap>You're welcome.",
                        16: "<wrap>Um...",
                        18: "<wrap>What is it?",
                        21: "<wrap>This is for you.",
                        24: "<wrap>You want me to give this to Phainon?",
                        26: "<wrap>Yes!",
                        28: "<wrap>Then I'm off. Goodbye, fairies.",
                        32: "<wrap>Lord Demigod, we little fairies can't really help with the disasters outside, but we wish you and your heroic comrades a triumphant return.",
                        36: "<wrap>We will. Phainon's efforts won't be in vain. Let's meet again in the new world.",
                        39: "<wrap>(The oracle card is restless. Move farther away from them to check it.)",
                    },
                },
            },
            6: {
                24: {
                    0: {
                        2: "好像迷路了，也许那封稚嫩的信件里有提示",
                    },
                },
                37: {
                    0: {
                        14: "迷路迷境的小妖精趁着黑暗抢走了神谕牌！",
                        16: "抓住它！",
                    },
                },
            },
            7: {
                8: {
                    0: {
                        5: "请查看神谕牌",
                    },
                },
            },
            8: {
                1: {
                    0: {
                        1: "（一段白厄和遐蝶的对话）",
                    },
                },
                2: {
                    0: {
                        1: "（一段白厄和风堇的对话）",
                    },
                },
                3: {
                    0: {
                        1: "（一段白厄和阿格莱雅、缇宝的对话",
                        3: "（然后告诉你那刻夏需要某个东西",
                    },
                },
                5: {
                    0: {
                        2: "那刻夏：跟我来",
                        7: "那刻夏：我要的东西呢",
                    },
                    1: {
                        1: "一段那刻夏和赛飞儿的剧情",
                    },
                },
                8: {
                    0: {
                        1: "这里未来会放个解密，",
                        2: "需要进入右侧房间解密才能拿到道具",
                        5: "但现在没想好怎么解密所以直接给你了。",
                    },
                    1: {
                        1: "东西已经拿到了，去找那刻夏吧。",
                        2: "这里未来会放个解密，现在没想好放什么，",
                        3: "也没想好地图。所以堵着不让过！",
                    },
                },
            },
            9: {
                3: {
                    0: {
                        6: "要悬锋字典",
                        8: "（一段剧情，大意：",
                        9: "存放字典的地方就在右侧，但已经被毁了",
                        11: "（一段剧情，大意：",
                        12: "通过左侧的欧洛尼斯宝珠（钻石）进入",
                        13: "万敌的记忆，回到正常的图书馆。",
                        14: "这样，右侧的地方就是复原的了。",
                    },
                },
                10: {
                    0: {
                        1: "前面是乱七八糟的废墟，需要从中找路",
                        2: "记得存档",
                    },
                },
                11: {
                    0: {
                        1: "重走迷宫？",
                    },
                },
            },
            10: {
                4: {
                    0: {
                        5: "一段剧情，大意：",
                        6: "被锁住了，要钥匙",
                    },
                },
                8: {
                    0: {
                        2: "门从另一个方向锁住了",
                    },
                },
                10: {
                    0: {
                        5: "放工具书的房间在右边",
                    },
                },
            },
            11: {
                9: {
                    0: {
                        1: "这是个火种匣，解开后里面有负世火种",
                        2: "觉得拼乱了可以点【重来】",
                        3: "或者看看万敌有什么办法",
                        20: "负世火种给你了",
                    },
                },
                15: {
                    0: {
                        1: "一些剧情",
                    },
                },
                17: {
                    0: {
                        1: "这里未来想做一个别关卡",
                        2: "但现在暂时没想好怎么做",
                        3: "所以先晾在这",
                        5: "完成关卡后，黑厄会入队。",
                        6: "但没想好这个剧情怎么接。总之先把黑厄给你",
                    },
                },
                18: {
                    0: {
                        1: "这里是黑夜版黎明云崖",
                        2: "靠近黑潮怪会导致忆质剧烈波动，得想办法引开它们",
                    },
                },
            },
            12: {
                2: {
                    0: {
                        2: "流程结束，感谢测试！",
                        3: "可以点开反馈文档看一下！",
                    },
                },
            },
            15: {
                1: {
                    0: {
                        3: "小妖精：可恶！怎么追上来了！",
                        5: "万敌：还想跑！？",
                    },
                    2: {
                        1: "万敌：把牌还我",
                    },
                },
                2: {
                    0: {
                        5: "请查看神谕牌",
                    },
                },
            },
            16: {
                1: {
                    0: {
                        8: "Pre-game Tips:",
                        9: "<wrap>It's a test version with only the framework done, see the changelog for details.",
                        10: "<wrap>Note down any issues, and after finishing, go settle scores with the author (?",
                        12: "<wrap>Can you hear me?",
                        14: "<wrap>...dei? Lord... Mydeimos? Wake up——",
                        16: "...",
                        18: "<wrap>Oh dear... Do I really have to separate them manually...",
                        20: "<wrap>Phainon?",
                        22: "<wrap>Huh? Awake now!",
                        24: "<wrap>Sorry, but I'm not the Deliverer you've been longing for. Sorry to wake you up so suddenly.",
                        26: "<wrap>? Mem? No, Miss Cyrene?",
                        28: "<wrap>When is the next recreation? Where is this? What do you want me to do?",
                        30: "<wrap>...Ah, Mydei is as straightforward as ever.",
                        32: "<wrap>You can think of this place as a maze of someone's memories.",
                        34: "<wrap>My friends are on their way, and I'm preparing for the final recreation. But I found that your memories are intertwined with someone else's memory mass, inseparable.",
                        36: "<wrap>If this tangled code isn't sorted out, there might be problems during the recreation.",
                        38: "<wrap>I dare not forcibly separate you, and I can't wake the other person's consciousness... so I woke you up to see if you can unravel it from the inside.",
                        40: "<wrap>I feel like something similar happened not too long ago...",
                        42: "<wrap>This space is very fragile. I could even directly—",
                        44: "<wrap>Hey hey hey wait wait!!",
                        46: "<wrap>As you said, this memory mass is indeed fragile, so we must be extra careful. That's why I especially emphasize—",
                        48: "<wrap>Absolutely no fighting here! We must outsmart it!",
                        50: "...",
                        52: "<wrap>You want a demigod of Strife to outsmart a memory maze.",
                        54: "<wrap>I haven't forgotten that in this cycle, you graduated from the Nousporist school. Outsmarting a maze sprouted from a Nouspore should be no problem!",
                        56: "<wrap>Then you probably haven't forgotten that to fight Lygus, I had Anaxagoras remove my brain.",
                        58: "<wrap>I haven't forgotten, so I woke up the you before the Soul-Rending! And I'll help you too—I can look up information from the outside!",
                        60: "<wrap>Never mind. Where do we start?",
                        62: "<wrap>Take a deep breath and dive into his maze.",
                    },
                },
            },
            17: {
                1: {
                    0: {
                        4: "(A CG will be added here later, currently not available)",
                        6: "<wrap>Let's start with the simplest salad.",
                        8: "<wrap>I love this! It tastes so sweet and refreshing!",
                        10: "<wrap>I like it too. This salad reminds me of the one Snowy made for us.",
                        12: "<wrap>Was the salad Phainon made for you like this?",
                        14: "<wrap>You haven't tried it?",
                        16: "<wrap>No, I've never even seen this Phainon you all talk about.",
                        18: "<wrap>This little blue fairy was only born in recent years, doesn't even have a name yet.",
                        20: "?",
                        22: "<wrap>(Recalling)<br>The fairies all know that whenever a major disaster happens in the outside world, one more fairy appears in the maze.",
                        24: "...?",
                        26: "<wrap>So how do you make this super delicious salad?",
                        28: "<wrap>Under Mydei's guidance, the little blue fairy slices the cured meat thinly, dices the potatoes and tomatoes into small pieces, shreds the lettuce, and shells the corn kernels. <br>After blanching the potato dices in boiling water, they are mixed with the other ingredients. Add seasoning, mix well. Ready to serve.",
                        30: "<wrap>Success!",
                        32: "<wrap>What's next? That bowl of sweet syrup? Drinking it feels so warm, like a sweet dream.",
                        34: "<wrap>Good taste. This is my favorite fig stew. ...Though it's a makeshift version.",
                        36: "<wrap>Makeshift version?",
                        38: "<wrap>Under Mydei's guidance, the little blue fairy chops the corn and potatoes finely, and cuts the dried honeyed fruit into thick shreds. <br>They are all put into clean water to simmer until the starch from the corn and potatoes thickens the water. <br>Add a few corn kernels for texture and a little bit of sugar. Ready to serve.",
                        40: "<wrap>So sweet, I love it!",
                        42: "<wrap>Not sweet enough yet, far from it. If you had fresh fig fruit, I could make it much sweeter and tastier.",
                        44: "<wrap>I think it's already very sweet, mew!",
                        46: "<wrap>It can be even sweeter? When will you bring fresh fig fruit? I want to try it!",
                        48: "<wrap>...Come to think of it, the chief said you don't have a name yet?",
                        50: "<wrap>You want to... give me a name? Okay!",
                        52: "<wrap>How about \"Fig Stew Mem\"?",
                        54: "<wrap>Wow! Then, I'm your favorite Fig Stew! Mem?",
                        56: "<wrap>Yeah.",
                        58: "<wrap>Let's make the most difficult one: the mixed stew.",
                        60: "<wrap>Okay!",
                        62: "<wrap>Under Mydei's guidance, Fig Stew Mem cuts all ingredients except the pod peas into large chunks. <br>First, fry the cured meat, then use the rendered oil to lightly stir-fry the pumpkin, potatoes, onions, and tomatoes. Add plenty of water to cover the ingredients. <br>After it boils, cover and simmer on low heat for minutes. <br>Finally, add the leafy greens, uncover, bring to a boil, and serve.",
                        64: "<wrap>The hardest dish, and it's a success!",
                        66: "<wrap>I love this one! All the ingredients are in there, rich and filling. Eating it gives a feeling of harvest happiness!",
                        68: "<wrap>Stew whatever you have, let the ingredients themselves handle the seasoning. It's truly a gift from nature, mew! Praise the Titan of cuisine!",
                        70: "<wrap>Is there such a Titan...",
                        72: "<wrap>This dish is nothing special. It's the most common way I stew during marches—convenient and tasty. It always wins the soldiers' praise.",
                        74: "<wrap>Marches?",
                        76: "<wrap>Right, you and Snowy are comrades. You must have marched to many places together, right?",
                        78: "<wrap>Hmm...",
                        80: "<wrap>I want to hear your march stories!",
                        82: "<wrap>(In this cycle, I never actually got to meet Phainon... but, I do have plenty of other stories to tell.)",
                        84: "<wrap>Alright. Let's take the dishes to the table and eat together while we talk.",
                        86: "<wrap>Yay!!!",
                        88: "<wrap>The Membrance Maze buzzes with rare liveliness. The fairies feast on the fragrant Kremnoan stew, their chatter flowing freely. <br>Listening to the little fairies talk nineteen to the dozen about Phainon's childhood mishaps, Mydei's hands never stop, but the corner of his mouth twitches ever so slightly. This HKS has always been a handful since he was little.",
                        91: "<wrap>Mydei shares with the fairies stories of his marches abroad, and tales of how the Chrysos Heirs, following the plans set by Cyrene and Aglaea, took turns fighting Lygus. The fairies listen, excited and tense.",
                        93: "<wrap>To avoid ruining the cheerful, lively atmosphere, Mydei glosses over the ending: <br>\"Right now, my comrades and I are preparing for the final battle. Cyrene said there was still some time, so she sent me here to find you. Later, once I reunite with Phainon, we'll be able to take down the enemy together.\"",
                        96: "<wrap>\"This is so wonderful, it feels like we've had such a lively banquet in a dream before,\" the fairies praise. As the food disappears, this impromptu little feast gradually comes to an end. The fairy chief directs the little fairies to clean up, while she floats over to thank Mydei.",
                    },
                },
            },
        },
        event_txt_Choices: {
            1: {
                32: {
                    0: {
                        3: ["了解", "我要提示", ],
                    },
                    1: {
                        3: ["了解", "我要提示", ],
                    },
                },
            },
            5: {
                3: {
                    0: {
                        18: ["触碰", ],
                    },
                },
            },
            9: {
                11: {
                    0: {
                        2: ["是", "否", ],
                    },
                },
            },
            11: {
                9: {
                    0: {
                        17: ["砸烂它！！", "继续拼！！", ],
                    },
                },
            },
        },
    },

};
